version: "3.8"
services: 
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - redis-net
    volumes:
      - redis-data:/data
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  postgresql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: citizens
    volumes:
      - ./script/:/docker-entrypoint-initdb.d/

networks:
  redis-net:

volumes:
  redis-data: